# Generated by Django 5.2.12 on 2026-03-30 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_auto_20260327_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=12)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='bookings.reserva')),
            ],
        ),
    ]
