# Generated by Django 5.2.12 on 2026-04-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='canal',
        ),
    ]
