# Generated by Django 5.2.12 on 2026-03-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
