# Generated by Django 5.2.11 on 2026-02-28 00:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Usa formato internacional con el + delante, ej: +34600111222.', regex='^\\+\\d{1,3}\\d{6,12}$')])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='customers.cliente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cliente', 'telefono'), name='unique_cliente_telefono')],
            },
        ),
    ]
