# Generated by Django 5.2.11 on 2026-03-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej. Ocean view, Estándar, Suite', max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField(help_text='Número máximo de personas')),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número o código de la habitación', max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la habitación', max_length=200)),
                ('estado', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('maintenance', 'Mantenimiento')], default='available', max_length=12)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.tipohabitacion')),
            ],
        ),
    ]
