# Generated by Django 5.2.11 on 2026-03-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Habitaciones'},
        ),
    ]
