# Generated by Django 5.2.11 on 2026-03-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_habitacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={},
        ),
    ]
