# Generated by Django 5.2.12 on 2026-03-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_habitacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Example: Ocean View, Standard, Suite', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(help_text='Maximum number of people')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Room number or code', max_length=10, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional room description', max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
            ],
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='TipoHabitacion',
        ),
    ]
