# Generated by Django 5.2.12 on 2026-03-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtype_room_delete_habitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='type',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name',
            field=models.CharField(blank=True, help_text='Example: Single Room, Double Room, Suite', max_length=50),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='rooms.amenity'),
        ),
    ]
