# Generated by Django 5.2.12 on 2026-03-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_amenity_remove_room_status_remove_roomtype_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
