# Generated by Django 5.2.12 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'Mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de servicio')], default='DISPONIBLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='meetings.sala')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sala', 'fecha', 'hora_inicio', 'hora_fin'), name='horario_sala_unico')],
            },
        ),
    ]
