# Generated by Django 5.2.12 on 2026-03-11

from django.db import migrations, models


def backfill_dia_semana(apps, schema_editor):
    HorarioSala = apps.get_model("meetings", "HorarioSala")
    for horario in HorarioSala.objects.all():
        if horario.fecha:
            horario.dia_semana = horario.fecha.weekday()
            horario.save(update_fields=["dia_semana"])


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="horariosala",
            name="horario_sala_unico",
        ),
        migrations.AddField(
            model_name="horariosala",
            name="dia_semana",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miercoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sabado"),
                    (6, "Domingo"),
                ],
                null=True,
            ),
        ),
        migrations.RunPython(backfill_dia_semana, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="horariosala",
            name="dia_semana",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miercoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sabado"),
                    (6, "Domingo"),
                ],
            ),
        ),
        migrations.RemoveField(
            model_name="horariosala",
            name="fecha",
        ),
        migrations.AddConstraint(
            model_name="horariosala",
            constraint=models.UniqueConstraint(
                fields=("sala", "dia_semana", "hora_inicio", "hora_fin"),
                name="horario_sala_unico",
            ),
        ),
    ]
