# Generated by Django 5.2.13 on 2026-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_horariosala_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
