# Generated by Django 5.2.13 on 2026-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
