# Generated by Django 5.2.13 on 2026-04-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='status',
        ),
    ]
